### PR TITLE
Rewrite GTK UI & Fix GTK UI Hang

### LINKED ISSUE #61: Use Faster Threading Primitives
# **crossbeam-channel** versus **std::sync::mpsc**

# parking_lot Mutex vs std Mutex

> Higher values are better

```
- Running with 1 threads
- 1 iterations inside lock, 0 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  60402.850 kHz |  61753.175 kHz |   1350.325 kHz
std::sync::Mutex     |  46016.558 kHz |  46626.734 kHz |    610.176 kHz
pthread_mutex_t      |  53268.642 kHz |  53359.425 kHz |     90.782 kHz
- Running with 2 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  29672.847 kHz |  35965.545 kHz |   6629.604 kHz
std::sync::Mutex     |   4099.018 kHz |   4642.389 kHz |    626.056 kHz
pthread_mutex_t      |   7086.428 kHz |   7230.676 kHz |    196.112 kHz
- Running with 3 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  19867.183 kHz |  24563.728 kHz |  10232.785 kHz
std::sync::Mutex     |   4136.010 kHz |   4175.220 kHz |     73.005 kHz
pthread_mutex_t      |   5045.504 kHz |   5090.151 kHz |     81.731 kHz
- Running with 4 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  14809.114 kHz |  17544.133 kHz |   7808.036 kHz
std::sync::Mutex     |   2118.016 kHz |   2125.304 kHz |     24.925 kHz
pthread_mutex_t      |   3104.926 kHz |   3142.101 kHz |     51.442 kHz
- Running with 5 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  11326.408 kHz |  13043.124 kHz |   6007.196 kHz
std::sync::Mutex     |   1675.045 kHz |   1702.958 kHz |     91.218 kHz
pthread_mutex_t      |   2285.452 kHz |   2316.768 kHz |    116.759 kHz
- Running with 6 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |   9424.928 kHz |  12319.226 kHz |   5667.318 kHz
std::sync::Mutex     |   1258.374 kHz |   1271.011 kHz |     34.273 kHz
pthread_mutex_t      |   1770.459 kHz |   1773.616 kHz |     68.696 kHz
- Running with 7 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |   7887.535 kHz |  10105.100 kHz |   4147.824 kHz
std::sync::Mutex     |   1043.273 kHz |   1038.135 kHz |     22.699 kHz
pthread_mutex_t      |   1482.260 kHz |   1473.764 kHz |     40.721 kHz
- Running with 8 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |   6739.492 kHz |   8044.099 kHz |   2204.661 kHz
std::sync::Mutex     |    890.111 kHz |    889.019 kHz |     13.639 kHz
pthread_mutex_t      |   1273.654 kHz |   1271.624 kHz |     23.562 kHz
```

# parking_lot RwLock vs std RwLock

> Higher values are better

```
- 1 iterations inside lock, 0 iterations outside lock
- 3 seconds per test
parking_lot::RwLock  - [write]      0.000 kHz [read]  52719.563 kHz
seqlock::SeqLock     - [write]      0.000 kHz [read] 236922.089 kHz
std::sync::RwLock    - [write]      0.000 kHz [read]  28657.696 kHz
pthread_rwlock_t     - [write]      0.000 kHz [read]  34604.594 kHz
- Running with 0 writer threads and 2 reader threads
parking_lot::RwLock  - [write]      0.000 kHz [read]  49628.359 kHz
seqlock::SeqLock     - [write]      0.000 kHz [read] 448663.138 kHz
std::sync::RwLock    - [write]      0.000 kHz [read]   7430.355 kHz
pthread_rwlock_t     - [write]      0.000 kHz [read]  10277.398 kHz
- Running with 0 writer threads and 3 reader threads
parking_lot::RwLock  - [write]      0.000 kHz [read]  48633.633 kHz
seqlock::SeqLock     - [write]      0.000 kHz [read] 668788.347 kHz
std::sync::RwLock    - [write]      0.000 kHz [read]   7526.618 kHz
pthread_rwlock_t     - [write]      0.000 kHz [read]   8301.649 kHz
- Running with 0 writer threads and 4 reader threads
parking_lot::RwLock  - [write]      0.000 kHz [read]  47424.554 kHz
seqlock::SeqLock     - [write]      0.000 kHz [read] 852084.755 kHz
std::sync::RwLock    - [write]      0.000 kHz [read]   7550.919 kHz
pthread_rwlock_t     - [write]      0.000 kHz [read]   6467.605 kHz
- Running with 1 writer threads and 0 reader threads
parking_lot::RwLock  - [write]  58991.526 kHz [read]      0.000 kHz
seqlock::SeqLock     - [write]  58952.036 kHz [read]      0.000 kHz
std::sync::RwLock    - [write]  30732.579 kHz [read]      0.000 kHz
pthread_rwlock_t     - [write]  34976.304 kHz [read]      0.000 kHz
- Running with 1 writer threads and 1 reader threads
parking_lot::RwLock  - [write]  60365.084 kHz [read]   2504.651 kHz
seqlock::SeqLock     - [write]  45803.276 kHz [read]   9734.377 kHz
std::sync::RwLock    - [write]    651.436 kHz [read]    601.020 kHz
pthread_rwlock_t     - [write]   4062.541 kHz [read]   4624.594 kHz
- Running with 1 writer threads and 2 reader threads
parking_lot::RwLock  - [write]  58498.529 kHz [read]   2530.441 kHz
seqlock::SeqLock     - [write]  36707.296 kHz [read]  22981.270 kHz
std::sync::RwLock    - [write]    156.200 kHz [read]   2048.605 kHz
pthread_rwlock_t     - [write]   2916.363 kHz [read]   5380.056 kHz
- Running with 1 writer threads and 3 reader threads
parking_lot::RwLock  - [write]  54709.932 kHz [read]   4259.414 kHz
seqlock::SeqLock     - [write]  31652.296 kHz [read]  20743.579 kHz
std::sync::RwLock    - [write]    108.414 kHz [read]   3471.831 kHz
pthread_rwlock_t     - [write]   1710.729 kHz [read]   4729.281 kHz
- Running with 1 writer threads and 4 reader threads
parking_lot::RwLock  - [write]  41931.769 kHz [read]  12514.711 kHz
seqlock::SeqLock     - [write]  27640.776 kHz [read]  31556.929 kHz
std::sync::RwLock    - [write]     42.332 kHz [read]   5662.952 kHz
pthread_rwlock_t     - [write]   1207.303 kHz [read]   4606.489 kHz
- Running with 2 writer threads and 0 reader threads
parking_lot::RwLock  - [write]  62614.957 kHz [read]      0.000 kHz
seqlock::SeqLock     - [write]  53983.536 kHz [read]      0.000 kHz
std::sync::RwLock    - [write]   7533.987 kHz [read]      0.000 kHz
pthread_rwlock_t     - [write]   8383.159 kHz [read]      0.000 kHz
- Running with 2 writer threads and 1 reader threads
parking_lot::RwLock  - [write]  58545.375 kHz [read]   2638.517 kHz
seqlock::SeqLock     - [write]  40492.168 kHz [read]  13461.550 kHz
std::sync::RwLock    - [write]    366.482 kHz [read]   1644.005 kHz
pthread_rwlock_t     - [write]   5472.980 kHz [read]   2835.566 kHz
- Running with 2 writer threads and 2 reader threads
parking_lot::RwLock  - [write]  57471.938 kHz [read]   1715.004 kHz
seqlock::SeqLock     - [write]  34525.371 kHz [read]  25672.695 kHz
std::sync::RwLock    - [write]    156.684 kHz [read]   1933.383 kHz
pthread_rwlock_t     - [write]   3300.043 kHz [read]   3011.416 kHz
- Running with 2 writer threads and 3 reader threads
parking_lot::RwLock  - [write]  48778.401 kHz [read]   7428.756 kHz
seqlock::SeqLock     - [write]  27742.067 kHz [read]  34696.893 kHz
std::sync::RwLock    - [write]    107.839 kHz [read]   3248.390 kHz
pthread_rwlock_t     - [write]   2314.413 kHz [read]   3457.917 kHz
- Running with 2 writer threads and 4 reader threads
parking_lot::RwLock  - [write]  47613.610 kHz [read]   7328.761 kHz
seqlock::SeqLock     - [write]  29363.052 kHz [read]  36264.828 kHz
std::sync::RwLock    - [write]     40.587 kHz [read]   5667.128 kHz
pthread_rwlock_t     - [write]   1754.821 kHz [read]   3544.354 kHz
- Running with 3 writer threads and 0 reader threads
parking_lot::RwLock  - [write]  61451.173 kHz [read]      0.000 kHz
seqlock::SeqLock     - [write]  48341.429 kHz [read]      0.000 kHz
std::sync::RwLock    - [write]   8349.189 kHz [read]      0.000 kHz
pthread_rwlock_t     - [write]   8228.863 kHz [read]      0.000 kHz
- Running with 3 writer threads and 1 reader threads
parking_lot::RwLock  - [write]  57919.760 kHz [read]   1144.595 kHz
seqlock::SeqLock     - [write]  36219.542 kHz [read]  15650.754 kHz
std::sync::RwLock    - [write]    223.381 kHz [read]    367.214 kHz
pthread_rwlock_t     - [write]   4946.966 kHz [read]   1472.755 kHz
- Running with 3 writer threads and 2 reader threads
parking_lot::RwLock  - [write]  52903.982 kHz [read]   4711.847 kHz
seqlock::SeqLock     - [write]  31673.358 kHz [read]  27105.980 kHz
std::sync::RwLock    - [write]    161.620 kHz [read]   2055.015 kHz
pthread_rwlock_t     - [write]   3474.153 kHz [read]   2317.335 kHz
- Running with 3 writer threads and 3 reader threads
parking_lot::RwLock  - [write]  49773.336 kHz [read]   5466.810 kHz
seqlock::SeqLock     - [write]  28000.003 kHz [read]  39288.238 kHz
std::sync::RwLock    - [write]    108.594 kHz [read]   3280.566 kHz
pthread_rwlock_t     - [write]   2682.776 kHz [read]   2661.312 kHz
- Running with 3 writer threads and 4 reader threads
parking_lot::RwLock  - [write]  48860.565 kHz [read]   5279.842 kHz
seqlock::SeqLock     - [write]  27043.554 kHz [read]  46468.848 kHz
std::sync::RwLock    - [write]     40.954 kHz [read]   5691.570 kHz
pthread_rwlock_t     - [write]   2152.390 kHz [read]   2724.305 kHz
- Running with 4 writer threads and 0 reader threads
parking_lot::RwLock  - [write]  58395.404 kHz [read]      0.000 kHz
seqlock::SeqLock     - [write]  42643.841 kHz [read]      0.000 kHz
std::sync::RwLock    - [write]   5878.185 kHz [read]      0.000 kHz
pthread_rwlock_t     - [write]   6334.077 kHz [read]      0.000 kHz
- Running with 4 writer threads and 1 reader threads
parking_lot::RwLock  - [write]  54407.372 kHz [read]   3683.116 kHz
seqlock::SeqLock     - [write]  32643.727 kHz [read]  18531.820 kHz
std::sync::RwLock    - [write]    249.974 kHz [read]    424.784 kHz
pthread_rwlock_t     - [write]   4633.299 kHz [read]   1162.709 kHz
- Running with 4 writer threads and 2 reader threads
parking_lot::RwLock  - [write]  53071.442 kHz [read]   3500.791 kHz
seqlock::SeqLock     - [write]  28644.046 kHz [read]  31088.420 kHz
std::sync::RwLock    - [write]    167.455 kHz [read]   1930.530 kHz
pthread_rwlock_t     - [write]   3521.325 kHz [read]   1799.898 kHz
- Running with 4 writer threads and 3 reader threads
parking_lot::RwLock  - [write]  49381.039 kHz [read]   5024.164 kHz
seqlock::SeqLock     - [write]  27936.083 kHz [read]  40144.285 kHz
std::sync::RwLock    - [write]    110.427 kHz [read]   3190.550 kHz
pthread_rwlock_t     - [write]   2833.992 kHz [read]   2096.695 kHz
- Running with 4 writer threads and 4 reader threads
parking_lot::RwLock  - [write]  39091.665 kHz [read]   2887.356 kHz
seqlock::SeqLock     - [write]  16447.604 kHz [read]  34305.151 kHz
std::sync::RwLock    - [write]     38.380 kHz [read]   5781.112 kHz
pthread_rwlock_t     - [write]   2350.162 kHz [read]   2278.875 kHz
```

### PR DESCRIPTION
**Pull request by mmstick**
Rewrites the GTK UI to use an event-driven approach.

Closes #61

### CODE REVIEW

**Comment by brs17** [comment]
@jackpot51 Unless you can show me how to recreate the deadlock, I would say you should go ahead and test the code and see if it fixes the issue you were having.

**Comment by jackpot51** [comment]
I still get the hang on clicking on the next button. Here is what it says in the terminal:

```
$ pkexec popsicle-gtk ~/Downloads/pop-os_18.04_amd64_intel_debug_85.iso
switching to device selection
```

**Comment by jackpot51** [comment]
It is likely caused by my USB SD card thingamajig. Maybe try one of those @brs17 ?

**Comment by mmstick** [comment]
May not be a deadlock. About to add some debug print statements that might give the answer.

**Comment by mmstick** [comment]
I suspect it's due to a card reader returning `0` as the number of sectors, and the loop condition that scans for that value not being `0` is in the incorrect order.

**Comment by mmstick** [comment]
This seems to have fixed it.

**Comment by mmstick** [comment]
:cry: I must have broken it with 85f0cdf

**Comment by mmstick** [comment]
Spent the weekend rewriting all of the logic in the GTK frontend. It now uses an event system similar to that in use by the receiving UI. There's much less moving pieces as a result, and this may have fixed the UI hanging.

**Comment by ahoneybun** [comment]
Latest push fixed the issue for me and going to see if the new live disk boots.

**Comment by mmstick** [comment]
I thought it might fix it. The previous design of the event system had potential for getting stuck in a lock, due to the large amounts of threads locking and unlocking the same locks in the background. Dynamically checking for the need to refresh devices on the device list caused a lot of overhead in additional bookkeeping.

The new design simply sends all UI events through channels to a single background thread, which later responds through a channel to a single GTK event loop in the main thread. That way, clicking a button doesn't spawn a new thread, but queues a new event to be handled in the background on an existing thread.

Seems those working on the GLib bindings for Rust have come to a similar conclusion, that a channel-based approach is more ideal for handling UI events. A new version of glib-rs will have it's own channel mechanism that can register with the glib main event loop.

File: gtk/src/app/signals/mod.rs [hunk 1]
```diff
@@ -0,0 +1,303 @@
...
+        let ui = self.ui.clone();
+
+        let mut last_device_refresh = Instant::now();
+        let mut flashing_devices: Vec<(gtk::ProgressBar, gtk::Label)> = Vec::new();
+        let flash_status = Arc::new(Atomic::new(FlashStatus::Inactive));
+        let mut flash_handles = None;
+        let mut tasks = None;
+
+        gtk::timeout_add(16, move || {
+            match state.ui_event_rx.try_recv() {
```
Comment (sdroege) [inline gtk/src/app/signals/mod.rs]: Instead of polling the channel, you probably want to properly integrate with the GLib main loop/context. You already use the crossbeam channel so probably care about performance, and this here kind of defeats the purpose.

Look how it's done in [glib-rs](https://github.com/gtk-rs/glib/blob/master/src/main_context_channel.rs) for the integrated channel.

Comment (mmstick) [reply gtk/src/app/signals/mod.rs]: Is that in a stable release yet?

Comment (sdroege) [reply gtk/src/app/signals/mod.rs]: Yes, in 0.7
